### ISSUE TITLE
404 is the result!

### ISSUE THREAD

**Issue by maggenti** [riad-azz/next-news-api#1]
Followed the instructions, and server started (easy part) and localhost 3000 says 404 This page could not be found. Hmm.... I must have missed something?

**Comment by riad-azz** [comment]
Oh yes the README.md has the wrong URL and has been corrected. 

Just go to [http://localhost:3000/api/news](http://localhost:3000/api/news) and you can see the news

**Comment by maggenti** [comment]
Thank you very much, YAY! This has helped me very much. Great Job, keep up the good work.
